### ISSUE TITLE
Decl instead of reffing fakeTDL

### ISSUE THREAD

**Issue by olabusayoT** [DFDLSchemas/faketdl#7]
Can we replace the ref of fakeTDL with a decl instead? Since we're using this for training, I figure we should use best practices?

https://github.com/DFDLSchemas/faketdl/blob/a4c63c17b490d90b33faff84521cc4a55cfa0e2a/src/fakeTDL.dfdl.xsd#L50C1-L50C98

**Comment by mbeckerle** [comment]
Done in one of the recent commits on my open PR.

**Comment by mbeckerle** [comment]
fixed in 4e4cf4fd71321048694b066ca714b6b944358b1b
